### ISSUE TITLE
NetworkCallback was already unregistered

### ISSUE THREAD

**Issue by StevenWatremez** [crisp-im/crisp-sdk-android#114]
# Context 
Same as the previous one we have an other crash that occurs 2 times for 2 users. 

# Crash log
```
Fatal Exception: java.lang.RuntimeException: Unable to stop activity {fr.leocare.app/im.crisp.client.ChatActivity}: java.lang.IllegalArgumentException: NetworkCallback was already unregistered
       at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4394)
       at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4364)
       at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4439)
       at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:41)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7078)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)


Caused by java.lang.IllegalArgumentException: NetworkCallback was already unregistered
       at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:47)
       at android.net.ConnectivityManager.unregisterNetworkCallback(ConnectivityManager.java:3886)
       at im.crisp.client.internal.d.b.b.c(:22)
       at im.crisp.client.ChatActivity.onStop(:4)
       at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1436)
       at android.app.Activity.performStop(Activity.java:7693)
       at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4386)
       at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4364)
       at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4439)
       at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:41)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7078)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)```
```

# Information
```
OS Version : Android 9
Phones : Galaxy A10, P20
SDK Version : 1.0.9
```

**Comment by StevenWatremez** [comment]
At this time in 7 days we had 10 crashes for 7 users.

**Comment by StevenWatremez** [comment]
Hi, no problem. Ah ok good to know 👍 thanks for this fix. I am waiting the next release 🎉

**Comment by Doc1faux** [comment]
@StevenWatremez `1.0.12` fixing this issue has just been released.
It can take a few hours before it will be available.
I close the issue.
