### ISSUE TITLE
Fragment not attached to a context.

### ISSUE THREAD

**Issue by kakarrot** [crisp-im/crisp-sdk-android#120]
### Crash logs

```
Fatal Exception: java.lang.IllegalStateException: Fragment a{f84e2b6} (6599091b-8ba9-4e3a-b201-9722c568007d) not attached to a context.
       at androidx.fragment.app.Fragment.requireContext(Fragment.java:17)
       at androidx.fragment.app.Fragment.getResources(Fragment.java)
       at im.crisp.client.internal.t.a.i(a.java:16)
       at im.crisp.client.internal.t.a.e(a.java)
       at im.crisp.client.internal.t.a$a.$r8$lambda$ZeEcfUBnpk_ZIy-RdAaZieLoxPU(a.java:2)
       at im.crisp.client.internal.t.a$a.$r8$lambda$vPyRWQAdeBq3CkmCfc6r_iPMy18(a.java)
       at im.crisp.client.internal.t.a$a$$InternalSyntheticLambda$0$a31a1181aba743b79fcce8116e67be87c0c0af6d28c0126261f802f4b8242299$2.run$bridge(a.java:18)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7590)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```
### Information
```
OS Version : Android 10
Phones : Redmi Note 7
SDK Version : 1.0.11
```

**Comment by Doc1faux** [comment]
Hi @kakarrot and thank you for your feedback.

It seems checking for an `Activity` before dispatching a `Runnable` on the `UiThread` is not enough to be sure the fragment is still attached when the `Runnable` will be dispatched... So I added an `isAdded()` check for methods which needs the fragment to be attached...

It will be released in the next 1.0.12.
I let you know when it will be available.
