### ISSUE TITLE
After Back from Crisp ChatActivity App Crash.

### ISSUE THREAD

**Issue by bhavikpatel93** [crisp-im/crisp-sdk-android#122]
Please fix this issue ASAP
 
 
 crispVersion = "1.0.9"
 
  java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/Player$EventListener;
        at im.crisp.client.internal.utils.b.a(Unknown Source:0)
        at im.crisp.client.Crisp.d(Unknown Source:0)
        at im.crisp.client.ChatActivity.onDestroy(Unknown Source:3)
        at android.app.Activity.performDestroy(Activity.java:8245)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1344)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5096)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5140)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by Doc1faux** [comment]
Hi @bhavikpatel93,

This crash has been fixed in `1.0.10` as stated in the #95 issue.
So please upgrade the Crisp SDK to this version at least.

I close the issue.
