### ISSUE TITLE
java.lang.SecurityException: Package android does not belong to 10365

### ISSUE THREAD

**Issue by pdprober** [crisp-im/crisp-sdk-android#131]
**OS Version** 
- Android 11

**Phones** 
- Galaxy A30s

**SDK Version** 
- 1.0.12 

**Crash logs**
Fatal Exception: java.lang.SecurityException: Package android does not belong to 10365
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2385)
       at android.os.Parcel.createException(Parcel.java:2369)
       at android.os.Parcel.readException(Parcel.java:2352)
       at android.os.Parcel.readException(Parcel.java:2294)
       at android.net.IConnectivityManager$Stub$Proxy.getNetworkCapabilities(IConnectivityManager.java:3347)
       at android.net.ConnectivityManager.getNetworkCapabilities(ConnectivityManager.java:1549)
       at im.crisp.client.internal.j.b.a(b.java:30)
       at im.crisp.client.internal.j.b.g(b.java:1)
       at im.crisp.client.internal.j.b.a(b.java)
       at im.crisp.client.internal.j.b.$r8$lambda$BqjSyhNbAYfISmizP2seWdwZnMY(b.java)
       at im.crisp.client.internal.j.b$$InternalSyntheticLambda$0$d252b559b99485ef900e1afab847d960b1f3c23a621c336f023dd29b14e3ce56$0.intercept(b.java)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:3)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:16)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:3)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:27)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:3)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:28)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:3)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:27)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:3)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.java:10)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.java:6)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

**Comment by Doc1faux** [comment]
HI @pdprober and thank you for your feedback.

This seems to be an Android SDK issue as per [Android Public Issue Tracker](https://issuetracker.google.com/issues/175055271) and has only be fixed in Android 12 (S), so the only existing workaround is to catch the `SecurityException` and silently fail :/

I've just pushed the update, it will be available in the next `1.0.13` release.

**Comment by Doc1faux** [comment]
@pdprober `1.0.13` fixing this issue has just been released.
It can take a few hours before it will be available.
I close the issue.
