### ISSUE TITLE
NullPointerExeception in Application initiate.How to solve this?

### ISSUE THREAD

**Issue by Karthikg206** [crisp-im/crisp-sdk-android#14]
Fatal Exception: java.lang.RuntimeException: Unable to create application com.example.android.SampleApplication: java.lang.NullPointerException
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6320)
       at android.app.ActivityThread.access$1800(ActivityThread.java:221)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7225)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by java.lang.NullPointerException
       at com.anupcowkur.reservoir.Reservoir.get(Reservoir.java:178)
       at im.crisp.sdk.stores.ContextStore.restore(SourceFile:54)
       at im.crisp.sdk.stores.ContextStore.<init>(SourceFile:33)
       at im.crisp.sdk.SharedCrisp.<init>(SourceFile:39)
       at im.crisp.sdk.SharedCrisp.initialize(SourceFile:49)
       at im.crisp.sdk.Crisp$Builder.initialize(SourceFile:73)
       at com.example.android.SampleApplication.onCreate(SampleApplication.java:71)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6317)
       at android.app.ActivityThread.access$1800(ActivityThread.java:221)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7225)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120).

**Comment by mywaystar** [comment]
Did you initialize the app like in the README?

Do you have the latest release?



--

Baptiste Jamin
CEO, Crisp <https://crisp.im/> - Connect your customers to your team.

On 19 Jan 2018, at 13:46, Karthikg206 <notifications@github.com> wrote:

Fatal Exception: java.lang.RuntimeException: Unable to create application com.example.android.SampleApplication: java.lang.NullPointerException
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6320)
at android.app.ActivityThread.access$1800(ActivityThread.java:221)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7225)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by java.lang.NullPointerException
at com.anupcowkur.reservoir.Reservoir.get(Reservoir.java:178)
at im.crisp.sdk.stores.ContextStore.restore(SourceFile:54)
at im.crisp.sdk.stores.ContextStore.(SourceFile:33)
at im.crisp.sdk.SharedCrisp.(SourceFile:39)
at im.crisp.sdk.SharedCrisp.initialize(SourceFile:49)
at im.crisp.sdk.Crisp$Builder.initialize(SourceFile:73)
at com.example.android.SampleApplication.onCreate(SampleApplication.java:71)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6317)
at android.app.ActivityThread.access$1800(ActivityThread.java:221)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7225)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120).

**Comment by mywaystar** [comment]
Lastest release is 0.1.1

**Comment by Karthikg206** [comment]
@mywaystar ok we will update but this build in live could you solve?

**Comment by Karthikg206** [comment]
@mywaystar in latest version how can i customize like primary color

**Comment by mywaystar** [comment]
By going to app.crisp.chat in the website settings.
--

Baptiste Jamin
CEO, Crisp <https://crisp.im/> - Connect your customers to your team.

On 19 Jan 2018, at 14:08, Karthikg206 <notifications@github.com> wrote:

@mywaystar <https://github.com/mywaystar> in latest version how can i customize like primary color
