### ISSUE TITLE
UnknownFormatConversionException 

### ISSUE THREAD

**Issue by mlecoq** [crisp-im/crisp-sdk-android#145]
Hi, 

i am using react-native bridge for crisp sdk (react-native-crisp-chat-sdk@0.11.1) and I have sometimes the following stacktrace in sentry 

```
 java.util.UnknownFormatConversionException: Conversion = ' '
    at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2782)
    at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2812)
    at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2625)
    at java.util.Formatter.parse(Formatter.java:2558)
    at java.util.Formatter.format(Formatter.java:2505)
    at java.util.Formatter.format(Formatter.java:2459)
    at java.lang.String.format(String.java:2911)
    at android.content.res.Resources.getQuantityString(Resources.java:663)
    at im.crisp.client.internal.utils.c.a
    at im.crisp.client.internal.ui.a.e.a
    at im.crisp.client.internal.ui.a.e.a
    at im.crisp.client.internal.ui.a.e.onCreateView
    at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
    at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
    at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138)
    at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:3065)
    at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2988)
    at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
    at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
    at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
    at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
    at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
    at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138)
    at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
    at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
    at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
    at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
    at im.crisp.client.ChatActivity.onStart
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
    at android.app.Activity.performStart(Activity.java:8231)
    at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3872)
    at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
    at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:246)
    at android.app.ActivityThread.main(ActivityThread.java:8653)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
````

**Comment by mlecoq** [comment]
Thanks for your quick answer, I will try it

**Comment by mlecoq** [comment]
@baptistejamin fyi I had a build issue with last release, I had to upgrade kotlin version from 1.5.20 to 1.6.10

**Comment by baptistejamin** [comment]
Do you have any error logs ?

**Comment by mlecoq** [comment]
```e: /Users/mlecoq/.gradle/caches/transforms-3/558bd884810cfdc9fc1b33caf02cd88f/transformed/jetified-kotlin-stdlib-common-1.7.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
e: /Users/mlecoq/.gradle/caches/transforms-3/a34ca149211c0683e9f71864e7bd0c8b/transformed/jetified-kotlin-stdlib-1.7.10.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
e: /Users/mlecoq/.gradle/caches/transforms-3/bb002c677a623d6cfa80228f72ba9133/transformed/appcompat-1.5.0-api.jar!/META-INF/appcompat_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
e: /Users/mlecoq/Developer/archireport/archireport-mobile/node_modules/react-native-crisp-chat-sdk/android/src/main/java/com/reactnativecrispchatsdk/CrispChatSdkModule.kt: (22, 15): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
The class is loaded from /Users/mlecoq/.gradle/caches/transforms-3/a34ca149211c0683e9f71864e7bd0c8b/transformed/jetified-kotlin-stdlib-1.7.10.jar!/kotlin/Unit.class
e: /Users/mlecoq/Developer/archireport/archireport-mobile/node_modules/react-native-crisp-chat-sdk/android/src/main/java/com/reactnativecrispchatsdk/CrispChatSdkModule.kt: (32, 15): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
The class is loaded from /Users/mlecoq/.gradle/caches/transforms-3/a34ca149211c0683e9f71864e7bd0c8b/transformed/jetified-kotlin-stdlib-1.7.10.jar!/kotlin/Unit.class
e: /Users/mlecoq/Developer/archireport/archireport-mobile/node_modules/react-native-crisp-chat-sdk/android/src/main/java/com/reactnativecrispchatsdk/CrispChatSdkModule.kt: (47, 15): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
The class is loaded from /Users/mlecoq/.gradle/caches/transforms-3/a34ca149211c0683e9f71864e7bd0c8b/transformed/jetified-kotlin-stdlib-1.7.10.jar!/kotlin/Unit.class
e: /Users/mlecoq/Developer/archireport/archireport-mobile/node_modules/react-native-crisp-chat-sdk/android/src/main/java/com/reactnativecrispchatsdk/CrispChatSdkModule.kt: (52, 15): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
The class is loaded from /Users/mlecoq/.gradle/caches/transforms-3/a34ca149211c0683e9f71864e7bd0c8b/transformed/jetified-kotlin-stdlib-1.7.10.jar!/kotlin/Unit.class
e: /Users/mlecoq/Developer/archireport/archireport-mobile/node_modules/react-native-crisp-chat-sdk/android/src/main/java/com/reactnativecrispchatsdk/CrispChatSdkModule.kt: (57, 15): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
The class is loaded from /Users/mlecoq/.gradle/caches/transforms-3/a34ca149211c0683e9f71864e7bd0c8b/transformed/jetified-kotlin-stdlib-1.7.10.jar!/kotlin/Unit.class
e: /Users/mlecoq/Developer/archireport/archireport-mobile/node_modules/react-native-crisp-chat-sdk/android/src/main/java/com/reactnativecrispchatsdk/CrispChatSdkModule.kt: (62, 15): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
The class is loaded from /Users/mlecoq/.gradle/caches/transforms-3/a34ca149211c0683e9f71864e7bd0c8b/transformed/jetified-kotlin-stdlib-1.7.10.jar!/kotlin/Unit.class
e: /Users/mlecoq/Developer/archireport/archireport-mobile/node_modules/react-native-crisp-chat-sdk/android/src/main/java/com/reactnativecrispchatsdk/CrispChatSdkModule.kt: (69, 7): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
The class is loaded from /Users/mlecoq/.gradle/caches/transforms-3/a34ca149211c0683e9f71864e7bd0c8b/transformed/jetified-kotlin-stdlib-1.7.10.jar!/kotlin/Unit.class
e: /Users/mlecoq/Developer/archireport/archireport-mobile/node_modules/react-native-crisp-chat-sdk/android/src/main/java/com/reactnativecrispchatsdk/CrispChatSdkModule.kt: (82, 13): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
The class is loaded from /Users/mlecoq/.gradle/caches/transforms-3/a34ca149211c0683e9f71864e7bd0c8b/transformed/jetified-kotlin-stdlib-1.7.10.jar!/kotlin/Unit.class
e: /Users/mlecoq/Developer/archireport/archireport-mobile/node_modules/react-native-crisp-chat-sdk/android/src/main/java/com/reactnativecrispchatsdk/CrispChatSdkModule.kt: (91, 15): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
The class is loaded from /Users/mlecoq/.gradle/caches/transforms-3/a34ca149211c0683e9f71864e7bd0c8b/transformed/jetified-kotlin-stdlib-1.7.10.jar!/kotlin/Unit.class
e: /Users/mlecoq/Developer/archireport/archireport-mobile/node_modules/react-native-crisp-chat-sdk/android/src/main/java/com/reactnativecrispchatsdk/CrispChatSdkModule.kt: (97, 63): Unresolved reference: java
e: /Users/mlecoq/Developer/archireport/archireport-mobile/node_modules/react-native-crisp-chat-sdk/android/src/main/java/com/reactnativecrispchatsdk/CrispChatSdkModule.kt: (99, 17): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
The class is loaded from /Users/mlecoq/.gradle/caches/transforms-3/a34ca149211c0683e9f71864e7bd0c8b/transformed/jetified-kotlin-stdlib-1.7.10.jar!/kotlin/Unit.class
e: /Users/mlecoq/Developer/archireport/archireport-mobile/node_modules/react-native-crisp-chat-sdk/android/src/main/java/com/reactnativecrispchatsdk/CrispChatSdkPackage.kt: (17, 14): Unresolved reference: emptyList

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-crisp-chat-sdk:compileDebugKotlin'.
> Compilation error. See log for more details``

**Comment by mlecoq** [comment]
The error does not occur anymore with last release of react-native sdk
