### ISSUE TITLE
error when reopen fragment

### ISSUE THREAD

**Issue by mortezasun** [crisp-im/crisp-sdk-android#16]
this error happened when reopen fragment

/Error: android.view.InflateException: Binary XML file line #16: Binary XML file line #16: Error inflating class fragment
                                                      Caused by: android.view.InflateException: Binary XML file line #16: Error inflating class fragment
                                                      Caused by: java.lang.IllegalArgumentException: Binary XML file line #16: Duplicate id 0xffffffff, tag crisp_fragment, or parent id 0x7f080121 with another fragment for im.crisp.sdk.ui.CrispFragment
                                                          at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2319)
                                                          at android.app.FragmentController.onCreateView(FragmentController.java:99)
                                                          at android.app.Activity.onCreateView(Activity.java:6093)
                                                          at android.support.v4.app.BaseFragmentActivityApi14.onCreateView(BaseFragmentActivityApi14.java:41)
                                                          at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:67)
                                                          at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:303)
                                                          at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:190)
                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:784)
                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
                                                          at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
                                                          at android.databinding.DataBindingUtil.inflate(DataBindingUtil.java:116)
                                                          at android.databinding.DataBindingUtil.inflate(DataBindingUtil.java:88)
                                                          at com.payava.clientcore.base.Base3Fragment.onCreateView(Base3Fragment.java:122)
                                                          at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
                                                          at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
                                                          at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
                                                          at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
                                                          at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
                                                          at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
                                                          at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
                                                          at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
                                                          at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
                                                          at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
                                                          at android.os.Handler.handleCallback(Handler.java:751)
                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                          at android.os.Looper.loop(Looper.java:154)
                                                          at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)

**Comment by mortezasun** [comment]
i use  xml fragment in fragment class 
error happened for this reason

**Comment by mywaystar** [comment]
You may have multiple crisp_fragments tags

**Comment by mortezasun** [comment]
how to handled message notification  in service app by crisp?
