### ISSUE TITLE
Exception in runtime

### ISSUE THREAD

**Issue by rezafaraji93** [crisp-im/crisp-sdk-android#161]
I get a Fatal Exception which I think it is related to Crisp:

`Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:355)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
       at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:784)

 

 

 

Caused by java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{b4e250c 31298:cash.bit24/u0a359} (pid=31298, uid=10359) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
       at android.os.Parcel.createException(Parcel.java:1953)
       at android.os.Parcel.readException(Parcel.java:1921)
       at android.os.Parcel.readException(Parcel.java:1871)
       at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:4159)
       at android.app.ActivityThread.acquireProvider(ActivityThread.java:6845)
       at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2922)
       at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1879)
       at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1460)
       at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1313)
       at android.content.ContentResolver.openInputStream(ContentResolver.java:1033)
       at im.crisp.client.internal.j.a.a(SourceFile:1)
       at im.crisp.client.internal.j.a.doInBackground(:2)
       at android.os.AsyncTask$2.call(AsyncTask.java:334)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
       at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:784)

 

 

 

Caused by android.os.RemoteException

Remote stack trace: at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:13626) at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:14121) at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:357) at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3654) at com.android.server.am.HwActivityManagerService.onTransact(HwActivityManagerService.java:609)

 

Caused by android.os.RemoteException: Remote stack trace:
    at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:13626)
    at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:14121)
    at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:357)
    at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3654)
    at com.android.server.am.HwActivityManagerService.onTransact(HwActivityManagerService.java:609)`

**Comment by Doc1faux** [comment]
Hi @rezafaraji93 and thank you for your feedback,

I already got this one on the Crisp app one time, it concerns the attachment upload (file and photo pickers).

As the URI permission is ephemeral, I suppose sometimes the socket can be a bit slow to respond (server or network) and if the user closes the chat and reopens it, the socket can reply on reconnect but the URI permission is not authorized anymore...
I only saw it one time on our Crashlytics so I suppose it's an edge-case like this. Do you reproduce it often?

Anyway, I'll fix this by catching the `SecurityException` and throwing a SnackBar error proposing to retry.

**Comment by rezafaraji93** [comment]
Hi @Doc1faux, Thank you for your reply. We are really waiting for this update, because we are getting this crash on our production. Thanks.

**Comment by Doc1faux** [comment]
`1.0.16` fixing this crash has just been released.
It can take a few hours before it will be available.
I close the issue.
