### ISSUE TITLE
Crash when opening the crisp message

### ISSUE THREAD

**Issue by reygie25** [crisp-im/crisp-sdk-android#185]
I'm getting this crash log once the crisp chat view opens.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String im.crisp.client.internal.data.b.d()' on a null object reference
                                     	at im.crisp.client.internal.data.ChatMessage.t(Unknown Source:12)
                                     	at im.crisp.client.internal.b.a.a(SourceFile:1)
                                     	at im.crisp.client.internal.h.b.a(SourceFile:27)
                                     	at im.crisp.client.internal.h.b.a(SourceFile:25)
                                     	at im.crisp.client.internal.h.b.c(SourceFile:6)
                                     	at im.crisp.client.internal.h.b.b(SourceFile:10)
                                     	at im.crisp.client.internal.h.b.a(SourceFile:25)
                                     	at im.crisp.client.internal.h.b.a(SourceFile:24)
                                     	at im.crisp.client.internal.h.a.a(SourceFile:8)
                                     	at im.crisp.client.internal.h.a.a(SourceFile:25)
                                     	at im.crisp.client.internal.h.a.c(SourceFile:4)
                                     	at im.crisp.client.internal.h.a.p(SourceFile:1)
                                     	at im.crisp.client.internal.h.a.$r8$lambda$JhVOR3VikYGPj6QfDtogpown5FM(Unknown Source:0)
                                     	at im.crisp.client.internal.h.a$$ExternalSyntheticLambda7.call(Unknown Source:2)
                                     	at io.socket.emitter.Emitter.emit(Emitter.java:117)
                                     	at io.socket.client.Socket.onevent(Socket.java:320)
                                     	at io.socket.client.Socket.onpacket(Socket.java:271)
                                     	at io.socket.client.Socket.access$100(Socket.java:18)
                                     	at io.socket.client.Socket$2$2.call(Socket.java:88)
                                     	at io.socket.emitter.Emitter.emit(Emitter.java:117)
                                     	at io.socket.client.Manager.ondecoded(Manager.java:361)
                                     	at io.socket.client.Manager.access$1200(Manager.java:22)
                                     	at io.socket.client.Manager$5.call(Manager.java:355)
                                     	at io.socket.parser.IOParser$Decoder.add(IOParser.java:103)
                                     	at io.socket.client.Manager$2.call(Manager.java:331)
                                     	at io.socket.emitter.Emitter.emit(Emitter.java:117)
                                     	at io.socket.engineio.client.Socket.onPacket(Socket.java:558)
                                     	at io.socket.engineio.client.Socket.access$1000(Socket.java:36)
                                     	at io.socket.engineio.client.Socket$5.call(Socket.java:337)
                                     	at io.socket.emitter.Emitter.emit(Emitter.java:117)
                                     	at io.socket.engineio.client.Transport.onPacket(Transport.java:124)
                                     	at io.socket.engineio.client.Transport.onData(Transport.java:116)
                                     	at io.socket.engineio.client.transports.WebSocket.access$100(WebSocket.java:23)
                                     	at io.socket.engineio.client.transports.WebSocket$1$2.run(WebSocket.java:73)
                                     	at io.socket.thread.EventThread$2.run(EventThread.java:80)
                                     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                     	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by Doc1faux** [comment]
Hi @reygie25,

This is a duplicate of the #180 you've already opened.
Sorry for the late, I'll release a new SDK version with only the latest fixes shortly!
