### ISSUE TITLE
CrispFragment line 279

### ISSUE THREAD

**Issue by nuhin-startern** [crisp-im/crisp-sdk-android#29]
I faced crashed on CrispFragment according to my crashlytics report. Can your team give a solution.
 
Title:
CrispFragment line 279
im.crisp.sdk.ui.CrispFragment.handleIntentToLink

Log:
Fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=fb-messenger://user/240822773292890/?intent_trigger=mme&nav=discover pkg=com.facebook.orca launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1844)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1649)
       at android.app.Activity.startActivityForResult(Activity.java:5061)
       at android.app.Activity.startActivityFromFragment(Activity.java:5046)
       at android.app.Activity$HostCallbacks.onStartActivityFromFragment(Activity.java:7563)
       at android.app.Fragment.startActivity(Fragment.java:1130)
       at android.app.Fragment.startActivity(Fragment.java:1109)
       at im.crisp.sdk.ui.CrispFragment.handleIntentToLink(SourceFile:279)
       at im.crisp.sdk.ui.CrispFragment$1.shouldOverrideUrlLoading(SourceFile:111)
       at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(PG:16)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:323)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:6816)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

I use implementation 'im.crisp:crisp-sdk:0.1.10'
This crash is not frequent but most of the crash is from Samsung device 
67% Galaxy A7(2017)
33% Galaxy J5(2016)

**Comment by baptistejamin** [comment]
We just published the early beta of the Crisp Android native SDK. You can find it here: https://github.com/crisp-im/crisp-sdk-android/tree/beta
