### ISSUE TITLE
Random Crash on CrispFragment

### ISSUE THREAD

**Issue by MartinCazares** [crisp-im/crisp-sdk-android#34]
Version: 'im.crisp:crisp-sdk:0.1.14'

Stacktrace:
Caused by android.view.InflateException: Binary XML file line #8: Error inflating class android.webkit.WebView
       at android.view.LayoutInflater.createView(LayoutInflater.java:633)
       at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at im.crisp.sdk.ui.CrispFragment.onCreateView(SourceFile:1)
       at android.app.Fragment.performCreateView(Fragment.java:2069)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:875)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1050)
       at android.app.FragmentManagerImpl.addFragment(FragmentManager.java:1152)
       at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2142)
       at android.app.Activity.onCreateView(Activity.java:5538)
       at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:337)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
       at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
       at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
       at com.donaumorgen.utel.front.crisp.CrispActivity.onCreate(CrispActivity.kt:12)
       at android.app.Activity.performCreate(Activity.java:6211)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2468)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2601)
       at android.app.ActivityThread.access$800(ActivityThread.java:178)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5637)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

Caused by android.content.res.Resources$NotFoundException: String resource ID #0x2040003
       at android.content.res.Resources.getText(Resources.java:330)
       at android.content.res.Resources.getString(Resources.java:428)
       at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:684)
       at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:608)
       at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:674)
       at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:823)
       at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:662)
       at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:597)
       at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:319)
       at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:104)
       at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:271)
       at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:131)
       at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:118)
       at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
       at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:115)
       at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:268)
       at android.webkit.WebView.<init>(WebView.java:591)
       at android.webkit.WebView.<init>(WebView.java:526)
       at android.webkit.WebView.<init>(WebView.java:509)
       at android.webkit.WebView.<init>(WebView.java:496)
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:607)
       at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
       at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at im.crisp.sdk.ui.CrispFragment.onCreateView(SourceFile:1)
       at android.app.Fragment.performCreateView(Fragment.java:2069)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:875)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1050)
       at android.app.FragmentManagerImpl.addFragment(FragmentManager.java:1152)
       at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2142)
       at android.app.Activity.onCreateView(Activity.java:5538)
       at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:337)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
       at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
       at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
       at com.donaumorgen.utel.front.crisp.CrispActivity.onCreate(CrispActivity.kt:12)
       at android.app.Activity.performCreate(Activity.java:6211)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2468)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2601)
       at android.app.ActivityThread.access$800(ActivityThread.java:178)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5637)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by baptistejamin** [comment]
We just published the early beta of the Crisp Android native SDK. You can find it here: https://github.com/crisp-im/crisp-sdk-android/tree/beta
