### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by FrantisekGazo** [crisp-im/crisp-sdk-android#45]
I'm sometimes getting `java.util.ConcurrentModificationException` when opening chat activity using `1.0.3` android sdk.

I'm using the same code as here –> https://github.com/crisp-im/crisp-sdk-android/issues/43#issuecomment-822598812

It's happening only sometimes. Can you please check your collection manipulation?

```
E/UncaughtException(10094): Restarting app
E/UncaughtException(10094): java.util.ConcurrentModificationException
E/UncaughtException(10094): 	at java.util.ArrayList$Itr.next(ArrayList.java:831)
E/UncaughtException(10094): 	at im.crisp.client.b.a.a.l(SourceFile)
E/UncaughtException(10094): 	at im.crisp.client.b.e.a.e.i.b(SourceFile)
E/UncaughtException(10094): 	at im.crisp.client.b.e.a.e.i.a(SourceFile)
E/UncaughtException(10094): 	at im.crisp.client.b.e.b.g$a.j(SourceFile)
E/UncaughtException(10094): 	at im.crisp.client.b.e.b.g$a.lambda$lk1FiT7iDBX4RDrwY9_3h-tuGnw(SourceFile)
E/UncaughtException(10094): 	at im.crisp.client.b.e.b.-$$Lambda$g$a$lk1FiT7iDBX4RDrwY9_3h-tuGnw.run(lambda)
E/UncaughtException(10094): 	at android.os.Handler.handleCallback(Handler.java:751)
E/UncaughtException(10094): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/UncaughtException(10094): 	at android.os.Looper.loop(Looper.java:154)
E/UncaughtException(10094): 	at android.app.ActivityThread.main(ActivityThread.java:6077)
E/UncaughtException(10094): 	at java.lang.reflect.Method.invoke(Native Method)
E/UncaughtException(10094): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
E/UncaughtException(10094): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
```

**Comment by FrantisekGazo** [comment]
cc @baptistejamin

**Comment by FrantisekGazo** [comment]
@baptistejamin any update on this please?

**Comment by baptistejamin** [comment]
Hello!


We recently released a 1.0.4 version.


Is it fixing your problem?

**Comment by FrantisekGazo** [comment]
thanks, I'll update and test.

**Comment by baptistejamin** [comment]
Sure :)

**Comment by baptistejamin** [comment]
No problem, please do let us know if it occurs again :)
