### ISSUE TITLE
Android app is crashed when  opening Crisp conversation

### ISSUE THREAD

**Issue by rootmediastep** [crisp-im/crisp-sdk-android#51]
I'm getting a java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.gson.JsonPrimitive.getAsString()' on a null object reference
at im.crisp.client.b.d.e.k.a(Unknown Source:14) . Full log below . 

`2021-05-06 09:44:53.491 7607-7735/com.mediastep.gosellseller E/AndroidRuntime: FATAL EXCEPTION: EventThread
Process: com.mediastep.gosellseller, PID: 7607
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.gson.JsonPrimitive.getAsString()' on a null object reference
at im.crisp.client.b.d.e.k.a(Unknown Source:14)
at im.crisp.client.b.d.e.k.deserialize(Unknown Source:0)
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
at com.google.gson.Gson.fromJson(Gson.java:932)
at com.google.gson.Gson.fromJson(Gson.java:1003)
at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
at im.crisp.client.b.d.e.a.a(Unknown Source:148)
at im.crisp.client.b.d.e.a.deserialize(Unknown Source:0)
at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
at com.google.gson.Gson.fromJson(Gson.java:932)`

**Comment by baptistejamin** [comment]
Hello !

What SDK version are you using?

**Comment by rootmediastep** [comment]
I am using 1.0.2

**Comment by baptistejamin** [comment]
Could you please update to 1.0.4 ? If should fix your issue.

**Comment by rootmediastep** [comment]
I'll do that. Will let you know if it fixes the issue .

**Comment by Doc1faux** [comment]
Thanks for your feedback, this has been addressed in 1.0.3
