### ISSUE TITLE
Loading Error: "RecyclerView: No attached; skipping layout"

### ISSUE THREAD

**Issue by mhadikz** [crisp-im/crisp-sdk-android#52]
Hi, I'm getting this error in my Logcat when open "ChatActivity.class":
RecyclerView: No adapter attached; skipping layout
This causes not being loaded chatbox. I upgraded my RecyclerView to:
"androidx.recyclerview:recyclerview:1.2.0" but it didn't work.
Also, I tried to find probable conflicts with other dependencies but I wasn't successful in solving this problem.
![Screenshot_1620469473](https://user-images.githubusercontent.com/22215824/117535922-7e012600-b00d-11eb-8407-8ed2cc1ed277.png)

**Comment by mhadikz** [comment]
> Would it be possible to contact our support from https://crisp.chat ?
> 
> If possible we'd like a sample of your project so we can reproduce the issue.

Unfortunately, I think it is impossible because we are implementing your SDK on our existing product. Please let me know if I can be of other help.

**Comment by mhadikz** [comment]
If I try to send a message in this situation this error will show in Logcat:

java.lang.IllegalStateException: no_session
        at im.crisp.client.b.b.b.<init>(Unknown Source:102)
        at im.crisp.client.b.b.b.a(Unknown Source:9)
        at im.crisp.client.b.b.b.b(Unknown Source:1)
        at im.crisp.client.b.e.b.b.h(Unknown Source:15)
        at im.crisp.client.b.e.b.b.b(Unknown Source:0)
        at im.crisp.client.b.e.b.b.lambda$plNANRczFvOkK_jYvVFjfE6U4OE(Unknown Source:0)
        at im.crisp.client.b.e.b.-$$Lambda$b$plNANRczFvOkK_jYvVFjfE6U4OE.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:6294)
        at android.view.View$PerformClick.run(View.java:24770)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
2021-05-11 17:13:32.261 10628-10713/com.nivo.personalaccounting E/GAv4: Successfully bound to service but never got onServiceConnected callback

**Comment by Doc1faux** [comment]
Hi @mhadikz, thanks for your feedback.
The crash you reported has been addressed in 1.0.5.
Did you managed to fix the RecyclerView issue since? Let me know :)
