### ISSUE TITLE
enum constant im.crisp.client.b.b.b$c$a.history is missing

### ISSUE THREAD

**Issue by FrantisekGazo** [crisp-im/crisp-sdk-android#53]
I see couple of crashes like this in our crashlitics system.
From additional data it looks like it happend when ChatActivity was opening.

```
java.lang.EnumConstantNotPresentException: enum constant im.crisp.client.b.b.b$c$a.history is missing
    at im.crisp.client.b.b.b$c.<init>(SourceFile)
    at im.crisp.client.b.d.e.j.a(SourceFile)
    at im.crisp.client.b.d.e.j.deserialize(SourceFile)
    at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
    at com.google.gson.Gson.fromJson(Gson.java:927)
    at com.google.gson.Gson.fromJson(Gson.java:994)
    at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
    at im.crisp.client.b.d.e.a.a(SourceFile)
    at im.crisp.client.b.d.e.a.deserialize(SourceFile)
    at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
    at com.google.gson.Gson.fromJson(Gson.java:927)
    at com.google.gson.Gson.fromJson(Gson.java:892)
    at com.google.gson.Gson.fromJson(Gson.java:841)
    at com.google.gson.Gson.fromJson(Gson.java:813)
    at im.crisp.client.b.d.c.a.a(SourceFile)
    at im.crisp.client.b.d.a.lambda$xIiNzj3dlDFJqMUOsb6V4QvPZBs(SourceFile:0)
    at im.crisp.client.b.d.a.lambda$J7IYerjC8mO-OSeWdtq1JI98djk(SourceFile:0)
    at im.crisp.client.b.d.-$$Lambda$a$J7IYerjC8mO-OSeWdtq1JI98djk.call(lambda)
    at io.socket.emitter.Emitter.emit(Emitter.java:117)
    at io.socket.client.Socket.onevent(Socket.java:338)
    at io.socket.client.Socket.onpacket(Socket.java:289)
    at io.socket.client.Socket.access$100(Socket.java:24)
    at io.socket.client.Socket$2$2.call(Socket.java:120)
    at io.socket.emitter.Emitter.emit(Emitter.java:117)
    at io.socket.client.Manager.ondecoded(Manager.java:427)
    at io.socket.client.Manager.access$1600(Manager.java:30)
    at io.socket.client.Manager$7.call(Manager.java:403)
    at io.socket.parser.IOParser$Decoder.add(IOParser.java:105)
    at io.socket.client.Manager.ondata(Manager.java:419)
    at io.socket.client.Manager.access$1000(Manager.java:30)
    at io.socket.client.Manager$2.call(Manager.java:370)
    at io.socket.emitter.Emitter.emit(Emitter.java:117)
    at io.socket.engineio.client.Socket.onPacket(Socket.java:551)
    at io.socket.engineio.client.Socket.access$1000(Socket.java:36)
    at io.socket.engineio.client.Socket$5.call(Socket.java:335)
    at io.socket.emitter.Emitter.emit(Emitter.java:117)
    at io.socket.engineio.client.Transport.onPacket(Transport.java:126)
    at io.socket.engineio.client.Transport.write(Transport.java:0)
    at io.socket.engineio.client.Transport.onData(Transport.java:118)
    at io.socket.engineio.client.transports.WebSocket.access$100(WebSocket.java:24)
    at io.socket.engineio.client.transports.WebSocket$1$2.run(WebSocket.java:71)
    at io.socket.thread.EventThread$2.run(EventThread.java:80)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)

com.google.gson.JsonParseException: java.lang.EnumConstantNotPresentException: enum constant im.crisp.client.b.b.b$c$a.history is missing
    at im.crisp.client.b.d.e.j.a(SourceFile)
    at im.crisp.client.b.d.e.j.deserialize(SourceFile)
    at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
    at com.google.gson.Gson.fromJson(Gson.java:927)
    at com.google.gson.Gson.fromJson(Gson.java:994)
    at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
    at im.crisp.client.b.d.e.a.a(SourceFile)
    at im.crisp.client.b.d.e.a.deserialize(SourceFile)
    at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
    at com.google.gson.Gson.fromJson(Gson.java:927)
    at com.google.gson.Gson.fromJson(Gson.java:892)
    at com.google.gson.Gson.fromJson(Gson.java:841)
    at com.google.gson.Gson.fromJson(Gson.java:813)
    at im.crisp.client.b.d.c.a.a(SourceFile)
    at im.crisp.client.b.d.a.lambda$xIiNzj3dlDFJqMUOsb6V4QvPZBs(SourceFile:0)
    at im.crisp.client.b.d.a.lambda$J7IYerjC8mO-OSeWdtq1JI98djk(SourceFile:0)
    at im.crisp.client.b.d.-$$Lambda$a$J7IYerjC8mO-OSeWdtq1JI98djk.call(lambda)
    at io.socket.emitter.Emitter.emit(Emitter.java:117)
    at io.socket.client.Socket.onevent(Socket.java:338)
    at io.socket.client.Socket.onpacket(Socket.java:289)
    at io.socket.client.Socket.access$100(Socket.java:24)
    at io.socket.client.Socket$2$2.call(Socket.java:120)
    at io.socket.emitter.Emitter.emit(Emitter.java:117)
    at io.socket.client.Manager.ondecoded(Manager.java:427)
    at io.socket.client.Manager.access$1600(Manager.java:30)
    at io.socket.client.Manager$7.call(Manager.java:403)
    at io.socket.parser.IOParser$Decoder.add(IOParser.java:105)
    at io.socket.client.Manager.ondata(Manager.java:419)
    at io.socket.client.Manager.access$1000(Manager.java:30)
    at io.socket.client.Manager$2.call(Manager.java:370)
    at io.socket.emitter.Emitter.emit(Emitter.java:117)
    at io.socket.engineio.client.Socket.onPacket(Socket.java:551)
    at io.socket.engineio.client.Socket.access$1000(Socket.java:36)
    at io.socket.engineio.client.Socket$5.call(Socket.java:335)
    at io.socket.emitter.Emitter.emit(Emitter.java:117)
    at io.socket.engineio.client.Transport.onPacket(Transport.java:126)
    at io.socket.engineio.client.Transport.write(Transport.java:0)
    at io.socket.engineio.client.Transport.onData(Transport.java:118)
    at io.socket.engineio.client.transports.WebSocket.access$100(WebSocket.java:24)
    at io.socket.engineio.client.transports.WebSocket$1$2.run(WebSocket.java:71)
    at io.socket.thread.EventThread$2.run(EventThread.java:80)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)

com.google.gson.JsonParseException: com.google.gson.JsonParseException: java.lang.EnumConstantNotPresentException: enum constant im.crisp.client.b.b.b$c$a.history is missing
    at im.crisp.client.b.d.e.a.a(SourceFile)
    at im.crisp.client.b.d.e.a.deserialize(SourceFile)
    at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
    at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
    at com.google.gson.Gson.fromJson(Gson.java:927)
    at com.google.gson.Gson.fromJson(Gson.java:892)
    at com.google.gson.Gson.fromJson(Gson.java:841)
    at com.google.gson.Gson.fromJson(Gson.java:813)
    at im.crisp.client.b.d.c.a.a(SourceFile)
    at im.crisp.client.b.d.a.lambda$xIiNzj3dlDFJqMUOsb6V4QvPZBs(SourceFile:0)
    at im.crisp.client.b.d.a.lambda$J7IYerjC8mO-OSeWdtq1JI98djk(SourceFile:0)
    at im.crisp.client.b.d.-$$Lambda$a$J7IYerjC8mO-OSeWdtq1JI98djk.call(lambda)
    at io.socket.emitter.Emitter.emit(Emitter.java:117)
    at io.socket.client.Socket.onevent(Socket.java:338)
    at io.socket.client.Socket.onpacket(Socket.java:289)
    at io.socket.client.Socket.access$100(Socket.java:24)
    at io.socket.client.Socket$2$2.call(Socket.java:120)
    at io.socket.emitter.Emitter.emit(Emitter.java:117)
    at io.socket.client.Manager.ondecoded(Manager.java:427)
    at io.socket.client.Manager.access$1600(Manager.java:30)
    at io.socket.client.Manager$7.call(Manager.java:403)
    at io.socket.parser.IOParser$Decoder.add(IOParser.java:105)
    at io.socket.client.Manager.ondata(Manager.java:419)
    at io.socket.client.Manager.access$1000(Manager.java:30)
    at io.socket.client.Manager$2.call(Manager.java:370)
    at io.socket.emitter.Emitter.emit(Emitter.java:117)
    at io.socket.engineio.client.Socket.onPacket(Socket.java:551)
    at io.socket.engineio.client.Socket.access$1000(Socket.java:36)
    at io.socket.engineio.client.Socket$5.call(Socket.java:335)
    at io.socket.emitter.Emitter.emit(Emitter.java:117)
    at io.socket.engineio.client.Transport.onPacket(Transport.java:126)
    at io.socket.engineio.client.Transport.write(Transport.java:0)
    at io.socket.engineio.client.Transport.onData(Transport.java:118)
    at io.socket.engineio.client.transports.WebSocket.access$100(WebSocket.java:24)
    at io.socket.engineio.client.transports.WebSocket$1$2.run(WebSocket.java:71)
    at io.socket.thread.EventThread$2.run(EventThread.java:80)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)
```

**Comment by FrantisekGazo** [comment]
Will reopen if I see this on newer version (switched to 1.0.7)
