### ISSUE TITLE
NullPointerException: Attempt to read from field 'im.crisp.client.b.b.j im.crisp.client.b.d.c.d.m.i' on a null object reference

### ISSUE THREAD

**Issue by FrantisekGazo** [crisp-im/crisp-sdk-android#55]
I see couple of crashes like this in our crashlitics system.
From additional data it looks like it happend when ChatActivity was opening.
Can you please look at it?

```
java.lang.NullPointerException: Attempt to read from field 'im.crisp.client.b.b.j im.crisp.client.b.d.c.d.m.i' on a null object reference
    at im.crisp.client.b.e.b.a$a.lambda$0s9hPCTr8UiMW3PNT6-rVRehJ_Q
    at im.crisp.client.b.e.b.a$a.lambda$3cHIYFhRVmvYulFGyLlSp0h9cbI
    at im.crisp.client.b.e.b.a$a.lambda$iCMs7V3HY8a5NNeD0MV9L2oKhY0
    at im.crisp.client.b.e.b.a$a.lambda$pu_ugLYzkxUP6Ny9yKOIO_uq19g
    at im.crisp.client.b.d.b.a
    at im.crisp.client.b.d.b.a
    at im.crisp.client.b.d.b.a
    at im.crisp.client.b.d.a.lambda$-tfNWcIcwjgUM5i9nuoFt0ur6WQ
    at im.crisp.client.b.d.a.lambda$-tfNWcIcwjgUM5i9nuoFt0ur6WQ
    at im.crisp.client.b.d.a.lambda$6Bwjd2IhWjRj7CNLjlrfFJILTrs
    at im.crisp.client.b.d.a.lambda$Iky-fLZDGIML-ujCxPsb1F48U-E
    at im.crisp.client.b.d.a.lambda$xIiNzj3dlDFJqMUOsb6V4QvPZBs
    at im.crisp.client.b.d.a.lambda$J7IYerjC8mO-OSeWdtq1JI98djk
    at im.crisp.client.b.d.-$$Lambda$a$J7IYerjC8mO-OSeWdtq1JI98djk.call(lambda)
    at io.socket.emitter.Emitter.emit(Emitter.java:117)
    at io.socket.client.Socket.onevent(Socket.java:338)
    at io.socket.client.Socket.onpacket(Socket.java:289)
    at io.socket.client.Socket.access$100(Socket.java:24)
    at io.socket.client.Socket$2$2.call(Socket.java:120)
    at io.socket.emitter.Emitter.emit(Emitter.java:117)
    at io.socket.client.Manager.ondecoded(Manager.java:427)
    at io.socket.client.Manager.access$1600(Manager.java:30)
    at io.socket.client.Manager$7.call(Manager.java:403)
    at io.socket.parser.IOParser$Decoder.add(IOParser.java:105)
    at io.socket.client.Manager.ondata(Manager.java:419)
    at io.socket.client.Manager.access$1000(Manager.java:30)
    at io.socket.client.Manager$2.call(Manager.java:370)
    at io.socket.emitter.Emitter.emit(Emitter.java:117)
    at io.socket.engineio.client.Socket.onPacket(Socket.java:551)
    at io.socket.engineio.client.Socket.access$1000(Socket.java:36)
    at io.socket.engineio.client.Socket$5.call(Socket.java:335)
    at io.socket.emitter.Emitter.emit(Emitter.java:117)
    at io.socket.engineio.client.Transport.onPacket(Transport.java:126)
    at io.socket.engineio.client.Transport.write(Transport.java:0)
    at io.socket.engineio.client.Transport.onData(Transport.java:118)
    at io.socket.engineio.client.transports.WebSocket.access$100(WebSocket.java:24)
    at io.socket.engineio.client.transports.WebSocket$1$2.run(WebSocket.java:71)
    at io.socket.thread.EventThread$2.run(EventThread.java:80)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)
```

**Comment by FrantisekGazo** [comment]
Will reopen if I see this on newer version (switched to 1.0.7)
