### ISSUE TITLE
App crash on loading chat conversation

### ISSUE THREAD

**Issue by sudhirsinghct** [crisp-im/crisp-sdk-android#64]
I am trying to integrate the Crisp sdk within our app. We are using version : "1.0.7" of the SDK. We encountered that for a few users the crisp sdk crashes when the user tries to open a chat window which has some preloaded text(earlier conversation) in it. 

I am able to reproduce the issue and following is the stack trace
```
07-20 16:53:05.492 31270 31346 W .basiccrispcha: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->getAlpnSelectedProtocol()[B (greylist-max-q,core-platform-api, reflection, denied)
07-20 16:53:05.492 31270 31346 W .basiccrispcha: Accessing hidden method Lcom/android/org/conscrypt/AbstractConscryptSocket;->getAlpnSelectedProtocol()[B (greylist-max-q, reflection, denied)
07-20 16:53:05.622 31270 31270 D AndroidRuntime: Shutting down VM
07-20 16:53:05.625 31270 31270 E AndroidRuntime: FATAL EXCEPTION: main
07-20 16:53:05.625 31270 31270 E AndroidRuntime: Process: com.basiccrispchat, PID: 31270
07-20 16:53:05.625 31270 31270 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:52)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at im.crisp.client.b.f.m.getSmiledString(Unknown Source:2)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at im.crisp.client.b.e.a.e.m.a(Unknown Source:2)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at im.crisp.client.b.e.a.e.i.onBindViewHolder(Unknown Source:196)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:675)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.view.View.layout(View.java:22900)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.view.View.layout(View.java:22900)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.view.View.layout(View.java:22900)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.view.View.layout(View.java:22900)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.view.View.layout(View.java:22900)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.view.View.layout(View.java:22900)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.view.View.layout(View.java:22900)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.view.View.layout(View.java:22900)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.view.View.layout(View.java:22900)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
07-20 16:53:05.625 31270 31270 E AndroidRuntime: 	at android.view.View.layout(View.java:22900)
07-20 16:53:05.626 31270 31270 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
07-20 16:53:05.626 31270 31270 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
07-20 16:53:05.626 31270 31270 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
07-20 16:53:05.626 31270 31270 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
07-20 16:53:05.626 31270 31270 E AndroidRuntime: 	at android.view.View.layout(View.java:22900)
07-20 16:53:05.626 31270 31270 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
07-20 16:53:05.626 31270 31270 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
07-20 16:53:05.626 31270 31270 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
07-20 16:53:05.626 31270 31270 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:820)
07-20 16:53:05.626 31270 31270 E AndroidRuntime: 	at android.view.View.layout(View.java:22900)
07-20 16:53:05.626 31270 31270 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:6389)
07-20 16:53:05.626 31270 31270 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3604)
07-20 16:53:05.626 31270 31270 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3072)
07-20 16:53:05.626 31270 31270 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2066)
07-20 16:53:05.626 31270 31270 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8404)
07-20 16:53:05.626 31270 31270 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
07-20 16:53:05.626 31270 31270 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
07-20 16:53:05.626 31270 31270 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:731)
07-20 16:53:05.626 31270 31270 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
07-20 16:53:05.626 31270 31270 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
07-20 16:53:05.626 31270 31270 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-20 16:53:05.626 31270 31270 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:250)
07-20 16:53:05.626 31270 31270 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7766)
07-20 16:53:05.626 31270 31270 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-20 16:53:05.626 31270 31270 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
07-20 16:53:05.626 31270 31270 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
07-20 16:53:05.631  2113 31349 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
07-20 16:53:05.631  2113  6431 W ActivityTaskManager:   Force finishing activity com.basiccrispchat/im.crisp.client.ChatActivity
```
The same crash doesn't happen when I remove the token id. Please let me know if you need any extra info

I have shared the sample with user data with support team in which this issue can be easily reproducible

**Comment by eliottvincent** [comment]
Sample application code for reference: https://drive.google.com/file/d/1i4GWz5KmYrLr8VmVV1m8GtODrqjgwuKB/view

**Comment by sudhirsinghct** [comment]
This code has website id for our product that was the reason I didn't upload it here

**Comment by eliottvincent** [comment]
My bad, deleted.

**Comment by sudhirsinghct** [comment]
@eliottvincent any update on this ticket?

**Comment by eliottvincent** [comment]
Hello @sudhirsinghct, the bug has been fixed, we're waiting to release a new version of the SDK.

**Comment by sudhirsinghct** [comment]
When is the expected release date?

**Comment by sudhirsinghct** [comment]
Any update on release of SDK?

**Comment by FrantisekGazo** [comment]
Any update please?

**Comment by baptistejamin** [comment]
Unfortunately we don't have any news on this for now.

We will try debugging this soon

**Comment by FrantisekGazo** [comment]
ok, thank you

**Comment by Doc1faux** [comment]
As the 1.0.8 (and even the 1.0.9) has been released, this should be fixed.
I close the issue, please reopen if the crash happens again.
