### ISSUE TITLE
Asking for Email and Phone every time after attaching any file or photo in the chat screen

### ISSUE THREAD

**Issue by osman-teamswork** [crisp-im/crisp-sdk-android#75]
I have implemented Crisp SDK in our android app. Before starting chat I have set user email by calling `Crisp.setUserEmail(user.email)`. But when I attached a file and come again to the chat screen, it's asking for email and phone every time. I have attached screenshots below. What should I do to solve this issue. 
![Screenshot_20210928-160641](https://user-images.githubusercontent.com/76420680/135072141-2a270a6b-a221-4604-a67e-00b72c8af23e.png)
p

**Comment by eliottvincent** [comment]
Hello Osma, thanks for reporting this issue. We'll have a look at it and get back to you.

**Comment by osman-teamswork** [comment]
Hello Guys, any update on this?

**Comment by eliottvincent** [comment]
Hello, no update for now. Our Android developer is working on the new Android app right now, he'll handle the SDK issues afterwards.

**Comment by osman-teamswork** [comment]
I am also getting crash while sending image in the chat. Below is the crash log from Crashlytics.

Device Info-->
Brand:vivo
Model:vivo 1920

Operating system-->
Version:Android 11



Fatal Exception: java.lang.IllegalArgumentException: height must be > 0
       at android.graphics.Bitmap.checkWidthHeight(Bitmap.java:470)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:891)
       at im.crisp.client.b.a.b.a(:84)
       at im.crisp.client.b.a.b.$r8$lambda$Afk5vhx2OEYcdQtXFGsI8XK2p3E()
       at im.crisp.client.b.a.b$$ExternalSyntheticLambda1.run(:12)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:257)
       at android.app.ActivityThread.main(ActivityThread.java:8218)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1016)
