### ISSUE TITLE
Error with Crisp 1.0.8 (also 1.0.7)

### ISSUE THREAD

**Issue by francescogatto** [crisp-im/crisp-sdk-android#87]
java.lang.IllegalArgumentException: width must be > 0
        at android.graphics.Bitmap.checkWidthHeight(Bitmap.java:447)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:863)
        at im.crisp.client.internal.cache.b.a(Unknown Source:84)
        at im.crisp.client.internal.cache.b.$r8$lambda$rsK2ChW6YGCPwBvtL9dBBDhgkZg(Unknown Source:0)
        at im.crisp.client.internal.cache.b$$ExternalSyntheticLambda1.run(Unknown Source:12)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8582)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)

**Comment by Doc1faux** [comment]
Hi @francescogatto and thank you for your feedback.
The issue has been addressed in 1.0.9.
I let you reopen the issue if you run into it again.
